### ISSUE TITLE
Argument of type 'Sound' is not assignable to parameter of type 'DisplayObject'

### ISSUE THREAD

**Issue by yunsii** [vnve/vnve#1]
Usage example encounter TS error:
![image](https://github.com/vnve/vnve/assets/18096089/352015e9-24f2-4a04-830a-4679a7777688)

**Comment by ForeverSc** [comment]
> Usage example encounter TS error:
> 
> ![image](https://github.com/vnve/vnve/assets/18096089/352015e9-24f2-4a04-830a-4679a7777688)
> 
> 

I forgot to update the example in readme. You should use `addSound` instead. I will update readme later.

**Comment by yunsii** [comment]
After deep investigation, I find out the solution 😂
