### ISSUE TITLE
现在这种是按场景设计的，如果我有背景音乐需要一直循环播放的情况下应该怎么处理好些？

### ISSUE THREAD

**Issue by yunsii** [vnve/vnve#3]
如题，难道分场景去切分具体场景的音频片段？感觉有点离谱 😂

**Comment by ForeverSc** [comment]
> 如题，难道分场景去切分具体场景的音频片段？感觉有点离谱 😂

这部分需要增加一个跨场景播放的选项，tick函数中要加个特殊逻辑。目前的话只能先输出画面，最后再拿其他软件加一下

**Comment by yunsii** [comment]
> 目前的话只能先输出画面，最后再拿其他软件加一下

这搞法感觉还不如像我说的分场景去截取音频判断，或者直接一步到位看看怎么在 tick 中实现这个特殊逻辑吧 🫠

**Comment by ForeverSc** [comment]
https://github.com/vnve/vnve/commit/048572cc423eea42b02be718180b31da8b07f104 已经支持跨场景播放，Sound增加一个untilEnd属性，当untilEnd为true时会跨场景播放。同时设置上loop为true，可以实现全局循环播放。
