### ISSUE TITLE
单场景下如何编排素材的进入与退出？

### ISSUE THREAD

**Issue by yunsii** [vnve/vnve#4]
目前我尝试用动画来实现的，参考项目内的例子给动画增加延迟，但是现在有个尴尬的情况是文字即使还没进入，到了延迟时间还是会执行一次退出动画导致了文字会闪烁一下。再到了文字的进入时间之后又能正常走完流程。是否应该同时延时进入和退出时间？

**Comment by yunsii** [comment]
单场景下，比如说同一个位置我需要渲染多个文本或者图片等，就需要先渲染一个，等前一个到了设定的时间再渲染下一个，这时候对于第二个要渲染出来的元素我是用动画来做的，比如说 FadeIn 延迟一定的时间再执行 😂

> 退出动画的延迟时间需要叠加上之前的进入动画加上需要等待的时间

那就是要把之前消耗的时间都叠加到后一个动画的开始和结束状态上咯？

**Comment by ForeverSc** [comment]
> 单场景下，比如说同一个位置我需要渲染多个文本或者图片等，就需要先渲染一个，等前一个到了设定的时间再渲染下一个，这时候对于第二个要渲染出来的元素我是用动画来做的，比如说 FadeIn 延迟一定的时间再执行 😂
> 
> 
> 
> > 退出动画的延迟时间需要叠加上之前的进入动画加上需要等待的时间
> 
> 
> 
> 那就是要把之前消耗的时间都叠加到后一个动画的开始和结束状态上咯？

是的，你可以理解为每新建一个动画，就会创建出一个新的从0开始的动画队列。 队列都是并行的，每个队列上面只有一个动画。
这部分其实不太好，算个临时方案，主要是一个队列中叠加动画在实际使用中，有用户反馈难以理解。不过在编程的场景下，动画依照次序执行比较符合逻辑😂

**Comment by yunsii** [comment]
我看项目源码以为只需要给结束状态加上延迟就好了，看来有纰漏，晚点尝试下 🫡

**Comment by yunsii** [comment]
开始跟结束都加上延迟之后正常了 👌

**Comment by yunsii** [comment]
现在我是通过给各种子元素加上动画来控制显隐的，理论上是不是应该在子元素的类实现上直接支持好一些？或者在场景类上直接控制是否渲染该子元素？

**Comment by ForeverSc** [comment]
> 现在我是通过给各种子元素加上动画来控制显隐的，理论上是不是应该在子元素的类实现上直接支持好一些？或者在场景类上直接控制是否渲染该子元素？

场景类上去控制其实也是可以的，但是需要增加一个新的概念了，类似子元素的生命周期来专门做控制子元素的渲染与销毁， 确实会比现在的性能上有好处，不需要一次性加载太多子元素。跟动画算是两个不同维度的属性了。

**Comment by yunsii** [comment]
是的，在场景上控制是更高层面的抽象了，而且同样涉及子元素的显隐动画，这个看起来目前优先级应该没那么高？

**Comment by ForeverSc** [comment]
对的，效果上动画应该都能满足的，可以算作后续的优化了
