### ISSUE TITLE
视频导出的时候有什么方式能够加速渲染？

### ISSUE THREAD

**Issue by yunsii** [vnve/vnve#6]
现在直接用浏览器导出有点太慢了，看起来是由于 ticker 单线程执行导致的，还有个一毫秒的延迟。有可能通过改成 worker 并发多帧渲染吗？

**Comment by ForeverSc** [comment]
目前延迟是为了不block主线程的UI操作，后续计划是会有两个worker，一个worker渲染，一个worker做encode，速度会快不少

**Comment by yunsii** [comment]
大佬看起来暂时也没时间去弄吧？理论上能实现多帧的并发渲染吗？

**Comment by ForeverSc** [comment]
暂时还没时间改这块儿，理论上是可以的，不过我估计耗时的卡点会在encode上，而不是render，所以即使开很多worker并发去render意义不会特别大

**Comment by yunsii** [comment]
https://github.com/vnve/vnve/blob/5e57b8f6167c80c553b4ec48ff8fc020bff07e9e/packages/core/src/Creator/Synthesizer.ts#L85-L117

看起来是我表达有误，这一块应该就是 encode 吧？可以并发多个 worker 去解析 imageSource 吗？

**Comment by ForeverSc** [comment]
理论上也是可以的，多开几个VideoEncoder worker同时去生产VideoEncodedChunk，不过可能还需要看看muxer上能否支持，整体需要做一套调度控制的逻辑才行

**Comment by yunsii** [comment]
https://github.com/vnve/vnve/blob/5e57b8f6167c80c553b4ec48ff8fc020bff07e9e/packages/core/src/Creator/Synthesizer.ts#L228-L247

那这一步算是 render 咯？看起来我得先尝试优化渲染性能问题了 😂

**Comment by ForeverSc** [comment]
这一步是封装视频，render是：https://github.com/vnve/vnve/blob/5e57b8f6167c80c553b4ec48ff8fc020bff07e9e/packages/core/src/Creator/index.ts#L97

**Comment by yunsii** [comment]
看来还得研究下 🫠

**Comment by yunsii** [comment]
刚才找到了导出太慢的原因，之前添加过 seeked 事件来保证导出视频符合预期 https://github.com/vnve/vnve/issues/2#issuecomment-2128994218

现在发现 currentTime 越大，seeked 耗时越久 😦 这就导致了导出视频会越来越慢，如果逻辑还是这样的话有什么更好的处理方式吗？或者说导出视频的时候得让 Video 元素拥有逐帧渲染的能力，而不是使用 currentTime 来控制？

**Comment by ForeverSc** [comment]
seek的速度应该不会很慢，是视频文件很大而且还没加载完么？

**Comment by yunsii** [comment]
我本地的，资源都是缓存的，但是 seek 时间基本就是在线性增加，很奇怪
![image](https://github.com/vnve/vnve/assets/18096089/88949c3f-71e2-4153-9e0b-ee68da14276e)

**Comment by ForeverSc** [comment]
确实有点奇怪，可以先不用合成，就循环seek，看看是否会有类似的问题，排除下合成的干扰。感觉有点像合成的影响，造成了性能下降

**Comment by yunsii** [comment]
https://github.com/vnve/vnve/blob/5e57b8f6167c80c553b4ec48ff8fc020bff07e9e/packages/core/src/Creator/Synthesizer.ts#L94-L100

是指的把这个注释掉吧？注释之后还是有这个问题 😂 给人的感觉就是每次都是从 0 开始 seek才会这样越来越慢

**Comment by ForeverSc** [comment]
可以单独写个页面，就只有一个video标签，然后循环seek看看会不会有延迟。只注释这里可能会有其他逻辑干扰

**Comment by yunsii** [comment]
有点神奇了，测试了两个 MP4 视频，一个是现在碰到 seeked 时间递增的视频，共计 8 秒，单独测试后发现行为一模一样， seeked 时间还是会逐步从 0 增加到 500 多毫秒。

另外测试了一个 49 秒的视频，发现它的行为不太一样，seeked 时间逐步从 0 增加 250 毫秒之后周期性循环 🫠 整不会了。

测试代码如下：

```ts
export const Page = () => {
  const videoRef = useRef<HTMLVideoElement>(null)

  const handleSeek = async () => {
    const targetVideoElement = videoRef.current

    if (!targetVideoElement) {
      return
    }

    const setCurrentTime = (timestamp: number) => {
      return new Promise<void>((resolve) => {
        const videoElement = targetVideoElement
        const start = Date.now()
        const internalSeekedCallback = () => {
          videoElement.removeEventListener('seeked', internalSeekedCallback)
          console.log('seeked', Date.now() - start)
          resolve()
        }
        videoElement.addEventListener('seeked', internalSeekedCallback)
        videoElement.currentTime = timestamp
      })
    }

    const totalVideoFrames = targetVideoElement.duration * 30
    for (let i = 0; i < totalVideoFrames; i++) {
      await setCurrentTime(i * (targetVideoElement.duration / totalVideoFrames))
    }
  }

  return (
    <div>
      <video ref={videoRef} src='/videos/video01.mp4' controls width={360} />
      <button onClick={handleSeek}>seek</button>
    </div>
  )
}

export default Page
```

**Comment by ForeverSc** [comment]
那这看起来就是浏览器video标签本身seek的坑了，可能和视频编码格式也有关系，估计不太好解决了，可能只能换实现方式了，晚点我也研究下看看

**Comment by yunsii** [comment]
输出一个 24 秒的视频，内部会连续渲染三个不同的视频，我本机的渲染时间是 180 秒左右，但是累计的 seeked 时间大概在 160 秒左右 😂

**Comment by ForeverSc** [comment]
看了下通过video标签没有什么特别好的办法，后续还是通过webcodecs decode来实现会好些。不过整体肯定耗时会多一点，因为无论哪个方案都要对视频做解码，是个相对耗时的操作。

**Comment by yunsii** [comment]
现在有个思路是在导出视频的时候把 Video 元素换成一个自定义的 VideoImg 的元素，这个元素 load 的时候会通过 mp4box 解析得到所有的视频帧，在 tick 的时候通过时间戳再选择合适的图片 texture 来更新。

核心逻辑都写完了，但是发现 pixi.js@v8 加载 base64 和 blob url 形式的图片都报错，自定义 format 和 loader 也是过了 😅 这就很尴尬了，看了 pixi.js 相关 issues，理论上应该支持的，看起来还得先解决 pixi.js 的问题...

**Comment by ForeverSc** [comment]
嗯嗯，mp4box提取出帧数据，用webcodecs decode出VideoFrame再重绘出一个图片就行了，项目里之前写了个针对7的BlobExt，用于加载blob资源，不懂对8是否有效

**Comment by yunsii** [comment]
- https://github.com/pixijs/pixijs/issues/8529
- https://github.com/pixijs/pixijs/issues/9568

理论上应该官方就支持了吧，我怎么测试都报错 😂 那我先看看 https://github.com/vnve/vnve/blob/5e57b8f6167c80c553b4ec48ff8fc020bff07e9e/packages/core/src/Assets/BlobExt.ts#L13-L36

**Comment by ForeverSc** [comment]
之前看过源码，至少7是没有支持的

**Comment by yunsii** [comment]
看了 v8 源码才知道怎么用了，官方确实是支持了，不过配置得整对，我昨天疯狂调试都没成功，看起来是排列组合配置的时候出了问题

```ts
Assets.load({
  src: 'blob:http://dev-adsdrive.com.localhost:3000/3e9f04ea-4309-4e39-b13b-d32be0e1d563',
  format: 'png',
  loadParser: 'loadTextures',
})
```

顺便把 BlobExt  移除了 😂

**Comment by yunsii** [comment]
看了 v8 源码才知道怎么用了，官方确实是支持了，不过配置得整对，我昨天疯狂调试都没成功，看起来是排列组合配置的时候出了问题

```ts
Assets.load({
  src: 'blob:http://localhost:3000/3e9f04ea-4309-4e39-b13b-d32be0e1d563',
  format: 'png',
  loadParser: 'loadTextures',
})
```

顺便把 BlobExt  移除了 😂

**Comment by yunsii** [comment]
VideoImg 逻辑跑通了，本地 3 分钟到 30 秒了，剩下的是处理视频背景透明了 🫠 参考 https://github.com/bilibili/WebAV/issues/30 看看怎么用 pixi.js 实现

**Comment by ForeverSc** [comment]
666，还带视频背景透明😂，越来越复杂了哈哈

**Comment by yunsii** [comment]
要合成呀 😂 现在研究怎么去绿幕

**Comment by yunsii** [comment]
> VideoImg 逻辑跑通了，本地 3 分钟到 30 秒了

尬住了，目前发现内存占用爆高，seek 的方案内存基本没啥变化 😂 VideoImg tick 处理即使调用了 this.texture.source.unload() 卸载上次加载的资源内存占用还是需要好几个 G，不卸载甚至能到十几个 G 😅 导出完成内存也不会降下来，好像 unload 资源没有完全生效的感觉……

**Comment by yunsii** [comment]
最后测试发现不能直接使用 this.texture.source.unload()，这个好像不能稳定保证卸载之前的资源，Assets.load 的通过 Assets.unload 来处理内存就没啥变化了 🫠

**Comment by ForeverSc** [comment]
内存上其实也还有挺多优化空间的😂，目前最终视频也是直接存在内存里的，有点受限。

**Comment by yunsii** [comment]
> 内存上其实也还有挺多优化空间的

目前我把我能优化的都优化了，框架层面还有挺多优化空间？能具体说说吗？

**Comment by ForeverSc** [comment]
大头就是最终生成的视频不应该存放在内存中，mp4-muxer有提供一个stream流式写入的方式，然后通过opfs逐步写入一个本地临时文件中，这样内存就不会随着产物线性增长

**Comment by yunsii** [comment]
目前我们生成的视频都不会太大，应该不会超过一分钟，这个问题影响不大，我本地导出一个二十多秒的视频用了大概 2G 内存，导出也才 20M 不到。

> VideoImg 逻辑跑通了，本地 3 分钟到 30 秒了

另外这个说法有误，合成时计算的时间没有算上资源预加载的时间，VideoImg 会在预加载阶段抽帧，抽帧大概用了 1 分钟，因此应该是 3 分钟到 1 分半的优化 😂

**Comment by ForeverSc** [comment]
嗯嗯，只要导出不大那还好。PR可以更新下哈，我合入下

**Comment by yunsii** [comment]
接入编辑器需要处理吗？目前还没理清楚逻辑 😂

**Comment by ForeverSc** [comment]
不用😂，编辑器部分我后面来加，坑有点多哈哈

**Comment by yunsii** [comment]
OK，这个周末我处理下
