### ISSUE TITLE
为什么视频导出的时候我显示编码错误

### ISSUE THREAD

**Issue by sugarbunengchi** [vnve/vnve#7]
如题，做完视频之后我想要导出，但是不能下载
!
![Screenshot_20240701_110249_com microsoft emmx](https://github.com/vnve/vnve/assets/174291166/0659f87f-d3a9-489b-b883-c1745c09f152)

**Comment by ForeverSc** [comment]
可以贴一下浏览器版本和系统版本，估计是移动端的兼容性问题，后续我看下。推荐还是优先用电脑哈
