### ISSUE TITLE
个人建议：将@vnve/core抽离出来，重点做pixijs转视频

### ISSUE THREAD

**Issue by johnbaoss** [vnve/vnve#8]
目前市面上在web端挺缺那种直接把js动画转视频的工具，至少我找不到，现在短视频那么火，你这个工具应该针对短视频做才有好的发展前景。

**Comment by johnbaoss** [comment]
pixijs转视频这块你已经打好了基础，建议先集中精力做成一个类似[pixijs/filters](https://github.com/pixijs/filters)的独立包，再整理一下文档，用这个给你的工具引流，基本上就能做起来了。

**Comment by johnbaoss** [comment]
我是搜pixijs video找到你这个工具的
![image](https://github.com/user-attachments/assets/f08c5e72-6483-4279-85c9-9b2b402485ad)

**Comment by ForeverSc** [comment]
新版本有考虑到这点，设计上内核部分会再做一次拆分，能让pixi的项目无感接入。等验证通过，会单独再提个包出来。
