### ISSUE TITLE
How to host vnve on my server?

### ISSUE THREAD

**Issue by damngood168** [vnve/vnve#9]
Dear Sirs,
How to host vnve on my server?
I always got a blank web page while cross site

**Comment by ForeverSc** [comment]
any detail errors?

**Comment by damngood168** [comment]
I saw error on Chrome console
[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808 已導向 http://202.5.253.173:5173/vnve/

**Comment by damngood168** [comment]
If I run on http://localhost:5173/vnve/, totally ok. If use http://202.5.253.173:5173/vnve/ ,then got the error
[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808 已導向 http://202.5.253.173:5173/vnve/

202.5.253.173 is my server ip

**Comment by damngood168** [comment]
I think it not the firewall issue

**Comment by damngood168** [comment]
我真的非常喜歡VNVE, 但是目前遇到這個問題。若您可以幫我解決這個問題，並製作成可上傳下載儲存的專案JSON
,雖然我知道VNVE是MIT,但我也願意付費,請您協助

**Comment by ForeverSc** [comment]
Perhaps you could try deploying it using HTTPS instead of HTTP.

**Comment by damngood168** [comment]
> Perhaps you could try deploying it using HTTPS instead of HTTP.

您說對了

**Comment by damngood168** [comment]
Https is right
